spring:
  application:
    name: HamsterPOS
  datasource:
    #    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    #    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
  rate:
    limit:
      capacity: 100