spring:
  application:
    name: HamsterPOS
  datasource:
    #    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DB}
    #    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    dev.chadinasser.hamsterpos: DEBUG
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  security:
    jwt:
      secret: ${JWT_SECRET}
      accessTokenExpiration: 86400000 # 1 day
      refreshTokenExpiration: 604800000 # 7 days
      cleanupScheduleInterval: 3600000 # 1 hour